name: uses 
on: 
  workflow_call:
    inputs:
      artifacts:
        type: string
        required: true 
        defualt: dist
    secrets:
      envPAT:
        required: false
    outputs:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts }}