name: uses 
on: 
  workflow_call:
    inputs:
      artifact:
        description: gfd
        required: false
        default: dist
        type: string 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code 
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact }}
